### ISSUE TITLE
Bug: Currency Conversion Issue in Budget Calculation

### ISSUE THREAD

**Issue by rezaplus** [maybe-finance/maybe#1653]
**Bug Description:**
There is a discrepancy between the transaction currency and the budget calculation currency. Specifically, as seen in the attached screenshot:

Transactions are recorded in TRY (Turkish Lira).
Budgets are calculated using the default currency (USD), without proper currency conversion.

This leads to misleading budget overspending values. For example:

Transaction: 13,000 TRY (correctly recorded).
Budget: 365 USD, leading to an inaccurate overspending calculation of $12,635 USD.

![Image](https://github.com/user-attachments/assets/490b7e69-2840-4c9c-8280-ddf81fbc0326)

**Comment by zachgoll** [comment]
@rezaplus thanks for the report!  Just to confirm—is your family currency set to `USD`, and a _subset_ of your accounts have transactions in TRY?

In other words, you're intending for the overall budget to be in USD and specifically commenting on how individual transactions are not properly rolled into the totals?

**Comment by rezaplus** [comment]
Hi @zachgoll  thanks for getting back to me!

Yes, my family currency is set to USD, but I have accounts with transactions in TRY.

I intend for the overall budget to remain in USD, but the issue is that individual transactions in TRY are not being properly converted into USD before being rolled into the totals. This causes the budget calculations to show inaccurate values and overspending warnings.

Let me know if you need more details or testing on my end!

**Comment by zachgoll** [comment]
@rezaplus got it, thanks for the detail!  That's all I need.

**Comment by zachgoll** [comment]
We may need to implement #1615 prior to being able to fix this because many of the budget calculations are run in fairly verbose queries, which will require joins on the `exchange_rates` table (and thus, will need those rates pre-loaded).

**Comment by rezaplus** [comment]
Hi @zachgoll,

Do you have any updates on the plan for fixing it? I noticed it was marked as high priority, so I wanted to check if there’s an estimated timeline for resolution.

**Comment by zachgoll** [comment]
@rezaplus yep this is still high priority; we've just been swamped with all sorts of issues as we've onboarded new users lately!  Hoping to get to this within the week.

**Comment by zachgoll** [comment]
@rezaplus this should be fixed in the latest version of the app:

https://github.com/user-attachments/assets/3ba7e471-327d-4f35-af2d-5ea0c30a3f4f

**Comment by skromez** [comment]
Thank you Zach! I was also waiting for this fix, upgrading it right now, really appreciate your work!

**Comment by rezaplus** [comment]
Hi @zachgoll,

Thanks for fixing this! I’ve checked it in the latest version, and it works as expected. 

Thank you

**Comment by lngmngx** [comment]
Hi @zachgoll, I'm still facing this issue with v0.4.3. It seems to happen only to certain currencies. My general currency is CNY, and HKD seems to be coverted correctly while USD is not.

![Image](https://github.com/user-attachments/assets/9dba6430-66d0-4629-96e5-ea4f54bcac39)

**Comment by zachgoll** [comment]
@lngmngx are these incorrect conversions flowing through to your budgets?  Or is the problem only present on the transactions page?

Can you confirm what your instance returns for the following query?

```sql
SELECT * FROM exchange_rates 
WHERE date = '2025-03-04' AND from_currency = 'USD' AND to_currency = 'CNY';
```

If that doesn't return anything or the rate is wrong, then you'll likely need to clear your data cache OR we have incorrect rates flowing from Synth.
