### ISSUE TITLE
Bug: Unable to access to Maybe (Self Hosted) due subscription bad behaviour

### ISSUE THREAD

**Issue by javiermartingonzalez** [maybe-finance/maybe#2187]
### General checklist

- [X] I have removed personal / sensitive data from screenshots and logs
- [ ] I have searched [existing issues](https://github.com/maybe-finance/maybe/issues?q=is:issue) and [discussions](https://github.com/maybe-finance/maybe/discussions) to ensure this is not a duplicate issue
    
### How are you using Maybe?

- [ ] I am a paying Maybe customer (hosted version)
  - Paying Maybe users can also open requests in Intercom (if there is sensitive info involved)
- [X] I am a self-hosted user

### Self hoster checklist

_Paying, hosted users should delete this entire section._

If you are a self-hosted user, please complete all of the information below.  Issues with incomplete information will be marked as `Needs Info` to help our small team prioritize bug fixes.

- Self hosted app commit SHA (find in user menu): 17fa5413f6c3ffd7fe1c450dc837ff7ee3ad8c9e
  - [X] I have confirmed that my app's commit is the latest version of Maybe
- Where are you hosting?
  - [ ] Render
  - [X] Docker Compose
  - [ ] Umbrel
  - [ ] Other (please specify)

---

## Bug description

After updating to that version, something seems wrong, perhaps related to: a51c4d2cbafab174a5b446a865382df3fcea689d

And I'm not able to access my Maybe instance. I can see the login page, but then, I'm redirected to **/subscription/upgrade** with the following message on body: **Feature disabled: subscriptions#upgrade**

I have the SELF_HOSTED = true, so it seems a problem with that new onboarding / subscriptions behaviour not working properly for self hosted users.

### To Reproduce

Be as specific as possible so Maybe maintainers can quickly reproduce the bug you're experiencing.

1. Go to Maybe service page
2. After login, I'm redirected to /subscription/upgrade  instead of dashboard
3. An error page is showed about a disable feature

### Expected behavior

To be able to access to my dashboard.

What is the intended behavior that you would expect?

### Screenshots and/or recordings

We highly recommend providing additional context with screenshots and/or screen recordings.  This will _significantly_ improve the chances of the bug being addressed and fixed quickly.

**Comment by faspina** [comment]
I just cranked up the maybe container on unraid and I am getting the same thing. I have a button that says Try maybe for 14 days after providing login info and name and what I want to do with Maybe

**Comment by sebfar9172** [comment]
Hello i have the same issu this morning

**Comment by cky798** [comment]
I have the same issue after the latest pull

**Comment by zachgoll** [comment]
@javiermartingonzalez thank you for the report.  Definitely see what's going on here, will get a fix in shortly.

**Comment by zachgoll** [comment]
This is fixed on the latest commit:

https://github.com/maybe-finance/maybe/commit/0c79b335f11d80c0c065663a9f6a8d6b477fa92f

**Comment by faspina** [comment]
When is the Docker container going to be updated?

**Comment by zachgoll** [comment]
@faspina it is already updated.  Just pull down the `latest` tag and you should be good to go.

**Comment by faspina** [comment]
Still not working for me
Brand new database ( I even dropped it to start over)
This image just pulled ghcr.io/maybe-finance/maybe:latest
I get to a screen that says "Try Maybe for 14 days" after walking through my user setup, and the what brings you to Maybe. It is stuck there and won't let me get past it

**Comment by faspina** [comment]
Still not working for me
Brand new database ( I even dropped it to start over)
This image just pulled ghcr.io/maybe-finance/maybe:latest
I get to a screen that says "Try Maybe for 14 days" after walking through
my user setup, and the what brings you to Maybe. It is stuck there and
won't let me get past it

**Comment by sample-usr** [comment]
@zachgoll Can confirm, still not working. I started with a brand new instance, also made sure that the docker image is the latest. But now, stuck at the trial screen like @faspina .

**Comment by sebfar9172** [comment]
By my side, that's works fine with the latest commit

**Comment by zachgoll** [comment]
@faspina can you confirm that this original issue is fixed though?  

You should not be seeing "Feature disabled: subscriptions#upgrade" anymore, correct?

I've pushed a separate fix for what you're describing below.  Once that Docker image deploys I believe this subsequent issue you're referring to will be fixed:

https://github.com/maybe-finance/maybe/commit/84eb2c90d45107caa64ab17f4c62712048d08368

**Comment by faspina** [comment]
That is correct, sorry for the confusion
