### ISSUE TITLE
Docker installation throwing error

### ISSUE THREAD

**Issue by shubhank-saxena** [maybe-finance/maybe#292]
Hello! I was trying to install the application using docker.
The command I ran - `docker build -t maybe .`

My system - `M1 Mac Air`

Error trace - 
```bash
 => ERROR [build 6/6] RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile                                                                                            0.5s
------
 > [build 6/6] RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile:
0.485 /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:14: [BUG] Segmentation fault at 0x0049ffffbba006c0
0.485 ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [aarch64-linux]
0.485
0.485 -- Control frame information -----------------------------------------------
0.485 c:0100 p:---- s:0547 e:000546 CFUNC  :resume
0.485 c:0099 p:0007 s:0543 E:001da0 BLOCK  /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:14 [FINISH]
0.485 c:0098 p:---- s:0540 e:000539 CFUNC  :synchronize
0.485 c:0097 p:0026 s:0536 E:001218 METHOD /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:12
0.485 c:0096 p:0007 s:0531 e:000530 CLASS  /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:18
0.485 c:0095 p:0025 s:0528 e:000527 TOP    /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:5 [FINISH]
0.485 c:0094 p:---- s:0525 e:000524 CFUNC  :require
0.485 c:0093 p:0030 s:0520 e:000519 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.485 c:0092 p:0131 s:0514 e:000513 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.485 c:0091 p:0041 s:0505 e:000504 TOP    /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/reentrant_read_write_lock.rb:7 [FINISH]
0.485 c:0090 p:---- s:0502 e:000501 CFUNC  :require
0.485 c:0089 p:0030 s:0497 e:000496 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.485 c:0088 p:0131 s:0491 e:000490 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.485 c:0087 p:0047 s:0482 e:000481 TOP    /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomics.rb:8 [FINISH]
0.485 c:0086 p:---- s:0479 e:000478 CFUNC  :require
0.485 c:0085 p:0030 s:0474 e:000473 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.485 c:0084 p:0131 s:0468 e:000467 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.485 c:0083 p:0029 s:0459 e:000458 TOP    /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent.rb:6 [FINISH]
0.485 c:0082 p:---- s:0456 e:000455 CFUNC  :require
0.485 c:0081 p:0030 s:0451 e:000450 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.485 c:0080 p:0131 s:0445 e:000444 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.485 c:0079 p:0005 s:0436 e:000435 TOP    /usr/local/bundle/ruby/3.3.0/gems/tzinfo-2.0.6/lib/tzinfo/string_deduper.rb:4 [FINISH]
0.485 c:0078 p:---- s:0433 e:000432 CFUNC  :require_relative
0.485 c:0077 p:0025 s:0428 e:000427 TOP    /usr/local/bundle/ruby/3.3.0/gems/tzinfo-2.0.6/lib/tzinfo.rb:25 [FINISH]
0.485 c:0076 p:---- s:0425 e:000424 CFUNC  :require
0.485 c:0075 p:0030 s:0420 e:000419 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.485 c:0074 p:0131 s:0414 e:000413 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.485 c:0073 p:0005 s:0405 e:000404 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/values/time_zone.rb:3 [FINISH]
0.485 c:0072 p:---- s:0402 e:000401 CFUNC  :require
0.485 c:0071 p:0030 s:0397 e:000396 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.485 c:0070 p:0131 s:0391 e:000390 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.485 c:0069 p:0017 s:0382 e:000381 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/core_ext/time/conversions.rb:5 [FINISH]
0.485 c:0068 p:---- s:0379 e:000378 CFUNC  :require
0.485 c:0067 p:0030 s:0374 e:000373 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.485 c:0066 p:0131 s:0368 e:000367 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.485 c:0065 p:0065 s:0359 e:000358 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/core_ext/object/json.rb:14 [FINISH]
0.485 c:0064 p:---- s:0356 e:000355 CFUNC  :require
0.485 c:0063 p:0030 s:0351 e:000350 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.485 c:0062 p:0131 s:0345 e:000344 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.485 c:0061 p:0005 s:0336 e:000335 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/json/encoding.rb:3 [FINISH]
0.485 c:0060 p:---- s:0333 e:000332 CFUNC  :require
0.485 c:0059 p:0030 s:0328 e:000327 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.485 c:0058 p:0131 s:0322 e:000321 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.485 c:0057 p:0011 s:0313 e:000312 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/json.rb:4 [FINISH]
0.485 c:0056 p:---- s:0310 e:000309 CFUNC  :require
0.485 c:0055 p:0030 s:0305 e:000304 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.485 c:0054 p:0131 s:0299 e:000298 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.485 c:0053 p:0011 s:0290 e:000289 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/messages/metadata.rb:4 [FINISH]
0.486 c:0052 p:---- s:0287 e:000286 CFUNC  :require_relative
0.486 c:0051 p:0011 s:0282 e:000281 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/messages/codec.rb:4 [FINISH]
0.486 c:0050 p:---- s:0279 e:000278 CFUNC  :require
0.486 c:0049 p:0030 s:0274 e:000273 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.486 c:0048 p:0131 s:0268 e:000267 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.486 c:0047 p:0023 s:0259 e:000258 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/message_encryptor.rb:6 [FINISH]
0.486 c:0046 p:---- s:0256 e:000255 CFUNC  :require
0.486 c:0045 p:0030 s:0251 e:000250 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.486 c:0044 p:0131 s:0245 e:000244 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.486 c:0043 p:0017 s:0236 e:000235 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/encrypted_file.rb:5 [FINISH]
0.486 c:0042 p:---- s:0233 e:000232 CFUNC  :require
0.486 c:0041 p:0030 s:0228 e:000227 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.486 c:0040 p:0131 s:0222 e:000221 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.486 c:0039 p:0011 s:0213 e:000212 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/encrypted_configuration.rb:4 [FINISH]
0.486 c:0038 p:---- s:0210 e:000209 CFUNC  :require
0.486 c:0037 p:0030 s:0205 e:000204 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.486 c:0036 p:0131 s:0199 e:000198 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.486 c:0035 p:0041 s:0190 e:000189 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/application.rb:9 [FINISH]
0.486 c:0034 p:---- s:0187 e:000186 CFUNC  :require
0.486 c:0033 p:0030 s:0182 e:000181 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.486 c:0032 p:0131 s:0176 e:000175 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.486 c:0031 p:0053 s:0167 e:000166 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails.rb:13 [FINISH]
0.486 c:0030 p:---- s:0164 e:000163 CFUNC  :require
0.486 c:0029 p:0030 s:0159 e:000158 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.486 c:0028 p:0131 s:0153 e:000152 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.486 c:0027 p:0005 s:0144 e:000143 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/all.rb:3 [FINISH]
0.486 c:0026 p:---- s:0141 e:000140 CFUNC  :require
0.486 c:0025 p:0030 s:0136 e:000135 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.486 c:0024 p:0131 s:0130 e:000129 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.486 c:0023 p:0011 s:0121 e:000120 TOP    /rails/config/application.rb:3 [FINISH]
0.486 c:0022 p:---- s:0118 e:000117 CFUNC  :require_relative
0.486 c:0021 p:0005 s:0113 e:000112 TOP    /rails/Rakefile:4 [FINISH]
0.486 c:0020 p:---- s:0110 e:000109 CFUNC  :load
0.486 c:0019 p:0005 s:0105 e:000104 METHOD /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/rake_module.rb:29
0.486 c:0018 p:0143 s:0100 e:000099 METHOD /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:734
0.486 c:0017 p:0003 s:0094 e:000093 BLOCK  /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:126
0.486 c:0016 p:0002 s:0091 e:000090 METHOD /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:208
0.486 c:0015 p:0004 s:0086 e:000085 METHOD /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:125
0.486 c:0014 p:0021 s:0082 e:000081 BLOCK  /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/commands/rake/rake_command.rb:43
0.486 c:0013 p:0023 s:0078 e:000077 METHOD /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/rake_module.rb:59
0.486 c:0012 p:0021 s:0072 e:000071 METHOD /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/commands/rake/rake_command.rb:41
0.486 c:0011 p:0010 s:0065 e:000064 METHOD /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/commands/rake/rake_command.rb:20
0.486 c:0010 p:0032 s:0058 e:000057 METHOD /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/command.rb:156
0.486 c:0009 p:0035 s:0051 e:000050 BLOCK  /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/command.rb:73
0.486 c:0008 p:0015 s:0048 e:000047 METHOD /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/command.rb:149
0.486 c:0007 p:0048 s:0042 e:000041 METHOD /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/command.rb:69
0.486 c:0006 p:0038 s:0031 e:000030 TOP    /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/commands.rb:18 [FINISH]
0.486 c:0005 p:---- s:0026 e:000025 CFUNC  :require
0.486 c:0004 p:0030 s:0021 e:000020 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
0.486 c:0003 p:0131 s:0015 e:000014 METHOD /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30
0.486 c:0002 p:0024 s:0006 e:000005 EVAL   ./bin/rails:4 [FINISH]
0.486 c:0001 p:0000 s:0003 E:000100 DUMMY  [FINISH]
0.486
0.486 -- Ruby level backtrace information ----------------------------------------
0.486 ./bin/rails:4:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/commands.rb:18:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/command.rb:69:in `invoke'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/command.rb:149:in `with_argv'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/command.rb:73:in `block in invoke'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/command.rb:156:in `invoke_rake'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/commands/rake/rake_command.rb:20:in `perform'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
0.486 /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/rake_module.rb:59:in `with_application'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
0.486 /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:125:in `load_rakefile'
0.486 /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
0.486 /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:126:in `block in load_rakefile'
0.486 /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:734:in `raw_load_rakefile'
0.486 /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/rake_module.rb:29:in `load_rakefile'
0.486 /usr/local/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/rake_module.rb:29:in `load'
0.486 /rails/Rakefile:4:in `<main>'
0.486 /rails/Rakefile:4:in `require_relative'
0.486 /rails/config/application.rb:3:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/all.rb:3:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails.rb:13:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/railties/lib/rails/application.rb:9:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/encrypted_configuration.rb:4:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/encrypted_file.rb:5:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/message_encryptor.rb:6:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/messages/codec.rb:4:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/messages/codec.rb:4:in `require_relative'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/messages/metadata.rb:4:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/json.rb:4:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/json/encoding.rb:3:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/core_ext/object/json.rb:14:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/core_ext/time/conversions.rb:5:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/bundler/gems/rails-3d132b855541/activesupport/lib/active_support/values/time_zone.rb:3:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/gems/tzinfo-2.0.6/lib/tzinfo.rb:25:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/tzinfo-2.0.6/lib/tzinfo.rb:25:in `require_relative'
0.486 /usr/local/bundle/ruby/3.3.0/gems/tzinfo-2.0.6/lib/tzinfo/string_deduper.rb:4:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent.rb:6:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomics.rb:8:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/reentrant_read_write_lock.rb:7:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
0.486 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
0.486 /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:5:in `<main>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:18:in `<module:Concurrent>'
0.486 /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:12:in `mutex_owned_per_thread?'
0.486 /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:12:in `synchronize'
0.486 /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:14:in `block in mutex_owned_per_thread?'
0.486 /usr/local/bundle/ruby/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:14:in `resume'
0.486
0.486 -- Threading information ---------------------------------------------------
0.486 Total ractor count: 1
0.486 Ruby thread count for this ractor: 1
0.486
0.486 -- Machine register context ------------------------------------------------
0.486   x0: 0x0000aaab1615fb50  x1: 0x0000aaab172aeb90  x2: 0x0000ffffc51f0e90
0.486   x3: 0x0000ffffa16fff60  x4: 0x0000ffffa1700018  x5: 0x0000ffffa1720000
0.486   x6: 0x0000ffffbbf4bb88  x7: 0x0000000000000000 x18: 0x0000000000000000
0.486  x19: 0x0000000000000000 x20: 0x0000000000000000 x21: 0x0000000000000000
0.486  x22: 0x0000000000000000 x23: 0x0000000000000000 x24: 0x0000000000000000
0.486  x25: 0x0000000000000000 x26: 0x0000000000000000 x27: 0x0000000000000000
0.486  x28: 0x0000000000000000 x29: 0x0000000000000000  sp: 0x0000ffffa1700000
0.486  fau: 0x0049ffffbba006c0
0.486
0.486 -- C level backtrace information -------------------------------------------
0.489 Segmentation fault
------
Dockerfile:37
--------------------
  35 |
  36 |     # Precompiling assets for production without requiring secret RAILS_MASTER_KEY
  37 | >>> RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
  38 |
  39 |
--------------------
ERROR: failed to solve: process "/bin/sh -c SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile" did not complete successfully: exit code: 139
```

Is there something missing in the steps to compile?  |
I would love to help you guys to document the process.

Thank you for this amazing project!

**Comment by robzolkos** [comment]
Fix incoming shortly.

**Comment by robzolkos** [comment]
@shubhank-saxena the Dockerfile is intended for production use - and there is currently an issue with Ruby 3.3.0 docker images running on Apple Silicon (this is fixed in the upcoming 3.3.1).  In the meantime, in development are you able to use the patched devcontainer Dockerfile?  I have a PR here https://github.com/maybe-finance/maybe/pull/293 that will introduce it.

**Comment by sg-s** [comment]
i have the same issue. @robzolkos what precisely is the workaround? how do i use the patched decvontainer dockerfile?

**Comment by robzolkos** [comment]
Open up the devcontainer with vscode (make sure the devcontainers extension is installed).  It should boot up.  If not please let me know the error messages you get.

**Comment by zachgoll** [comment]
Hey @shubhank-saxena just to confirm, are you trying to get this running for self-hosting?  Or local dev?

**Comment by shubhank-saxena** [comment]
Hey @zachgoll ! I am trying it locally on my system

**Comment by zachgoll** [comment]
@shubhank-saxena got it, I'm going to close this out as I believe this has been addressed in #293

**Comment by sg-s** [comment]
@robzolkos i'm clearly doing something wrong so any help appreciated. what i did:

1. copy the Dockerfile from .devcontainer to the project root
2. build image using `docker build -t maybe .`
3. run using `docker run -i -p 127.0.0.1:3000:3000/tcp maybe`

when i visit localhost:3000 i see nothing (i see the "The connection was reset" error message)

**Comment by sg-s** [comment]
i tried another approach and ran into another error:

1. built using `docker build -t maybe . --platform linux/amd64`
2. ran using `docker run -p 127.0.0.1:3000:3000/tcp maybe`

i get  this error:

```
bin/rails aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit` (ArgumentError)

        raise ArgumentError, "Missing `secret_key_base` for '#{Rails.env}' environment, set this string with `bin/rails credentials:edit`"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/rails/config/environment.rb:5:in `<main>'
Tasks: TOP => db:prepare => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by george-glessner** [comment]
I'm having issues with the docker install as well. Have tried the `Dockerfile` install as well as `docker compose` both in `.devcontainer` to no avail.

**Comment by robzolkos** [comment]
@sg-s @george-glessner  The README was updated recently with more thorough instructions on setting up a development environment for each operating system https://github.com/maybe-finance/maybe?tab=readme-ov-file#setup-guides

Please give those a try and if still not working we can pin point at which step it fails.

* Note: Building a docker image for the purposes of self-hosting etc is [not quite ready yet](https://github.com/maybe-finance/maybe?tab=readme-ov-file#self-hosting).
